name: swipeable_page_route_example
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  swipeable_page_route:
    path: ../

dev_dependencies:
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 622728f6ed745c8d9c3744293cdc157f7bdb3833

flutter:
  uses-material-design: true
